### ISSUE TITLE
Json pointer not supported

### ISSUE THREAD

**Issue by Leroy14** [groupon/json-schema-validator#5]
Hi,
I'm trying to validate a json file against a json schema. It works fine until I need to use schema referencing other schemas. The files structure would be something like:

Files | Description
------------ | -------------
schemaDir/               | the directory where are stored the schemas
- schemaA.json       | the main schema
- schemaB.json       | the schema referenced by the main schema

and schemaA looks like:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Collection of B",
    "type": "array",
    "items": {
      "$ref": "schemaB.json"
    }
}
```
Here is the error thrown during the build:
```
[ERROR]
com.github.fge.jsonschema.core.exceptions.ProcessingException: fatal: URI "schemaB.json#" is not absolute
    level: "fatal"
    uri: "schemaB.json#"
        at com.github.fge.jsonschema.core.load.SchemaLoader.get(SchemaLoader.java:163)
        at com.github.fge.jsonschema.core.load.RefResolver.rawProcess(RefResolver.java:114)
        at com.github.fge.jsonschema.core.load.RefResolver.rawProcess(RefResolver.java:51)
        at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:77)
        at com.github.fge.jsonschema.core.processing.RawProcessor.process(RawProcessor.java:41)
        at com.github.fge.jsonschema.core.processing.ProcessorChain$ProcessorMerger.process(ProcessorChain.java:189)
        at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
        at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
        at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at com.github.fge.jsonschema.core.processing.CachingProcessor.process(CachingProcessor.java:109)
        at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:107)
        at com.github.fge.jsonschema.processors.validation.ValidationChain.process(ValidationChain.java:57)
        at com.github.fge.jsonschema.core.processing.ProcessorMap$Mapper.process(ProcessorMap.java:166)
        at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
        at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:128)
        at com.github.fge.jsonschema.core.processing.CachingProcessor$1.load(CachingProcessor.java:120)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
```
Do you have any idea what could be wrong here? Is your plugin support JSON pointers?
Thank you for your help,
Best Regards,
PS: I can provide a maven project to reproduce the issue if needed.

**Comment by Leroy14** [comment]
Without any answer, I've moved to a working plugin.
Thx

**Comment by rsachin** [comment]
Hello Leroy14,  I'm experiencing same issue. Please share which plugin is working for you.
